### ISSUE TITLE
Crash when catching multiple pokemon.

### ISSUE THREAD

**Issue by PrestonLeeC** [timinc-cobble/cobblemon-capturexp#8]
I believe this mod has introduced a crash. Steps to reproduce: Start a battle, throw a pokeball, run away. Before that pokeball has finished wobbling, start a new battle, throw a pokeball. The crash report is simple: No battle could be found with the id: ###. Thank you!

**Comment by tmetcalfe89** [comment]
Hello @PrestonLeeC!
Thank you for describing the steps to replicate.
In order to complete your bug report, please attach a link to your full latest log. It helps me make sure I'm looking at the right issue, as well as get some context about the environment the issue's happening in.
